# Lab 2.1 — ExternalSecret: map key store -> K8s Secret `db-secret` (refresh 10s).
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-creds
  namespace: demo
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: aws-store
    kind: SecretStore
  target:
    name: db-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: demo/db/password
