apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: require-signed-w10-api
spec:
  images:
    - glob: "ghcr.io/taitri2004/w10-api**"
  authorities:
    - name: cosign-key
      key:
        data: |
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEKffJYTNAHSz8QkuRkhoI36ryZN8s
          /ygPeajZMA1ABNu/dPQ3Y+mQYh9NbwI8qm7WhhK0rForTDX1y11URK9m2Q==
